name: Build & Deploy Bot

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create temporary .env for build args
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker compose build

      - name: Push Docker image
        run: docker compose push

  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy container on VPS
        run: |
          ssh -i ~/.ssh/github_actions -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"

            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/binance-trader-backend:latest

            cat > ~/binance-trader-backend.env <<EOT
          BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET=${{ secrets.BINANCE_API_SECRET }}
          TELEGRAM_BOT_KEY=${{ secrets.TELEGRAM_BOT_KEY }}
          NODE_ENV=production
          EOT

            docker stop binance-trader-backend || true
            docker rm binance-trader-backend || true

            docker run -d \
              --name binance-trader-backend \
              --env-file ~/binance-trader-backend.env \
              ${{ secrets.DOCKER_HUB_USERNAME }}/binance-trader-backend:latest
          EOF
